### ISSUE TITLE
Cannot access supplementary material from SIMBA3D paper

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#10]
Hey Michael,
I was trying to access the supplementary material on biorxiv but don't see it anywhere. How do I access the supplementary materials?

**Comment by michael-m-rosenthal** [comment]
I don't see it on there either. I thought that it was posted at one time, but maybe I am mistaken.

The supplementary material is quite big. Maybe It wasn't uploaded because of the size.
