### ISSUE TITLE
I get empty .npz files?

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#7]
Hi Michael,

I am trying to run simba3d on my data matrix
[NXT-43_chr1_250kb_new.npy.tar.gz](https://github.com/nerettilab/SIMBA3D/files/2452585/NXT-43_chr1_250kb_new.npy.tar.gz)

using` python create_warmstarts_tasklist.py` 

[create_warmstarts_tasklist.py.tar.gz](https://github.com/nerettilab/SIMBA3D/files/2452592/create_warmstarts_tasklist.py.tar.gz)

to get 

[warmstart_tasklist_NXT-43_chr1_250kb.txt](https://github.com/nerettilab/SIMBA3D/files/2452590/warmstart_tasklist_NXT-43_chr1_250kb.txt)

Then i run
`(py27) [tshisode@darwin creating_tasklists_with_python]$ simba3d -r warmstart_tasklist_NXT-43_chr1_250kb.txt`

leading to empty output .npz files?
Any reason why is this happening?

**Comment by michael-m-rosenthal** [comment]
Empty? Like it won't load? 0 bytes?

**Comment by tarak77** [comment]
It doesnt look empty, but i am trying to extract the coordinates, by using

```
>>> data = np.load('lam1_7.npz')['summary'].item()
>>> X_evol = data['X_evol']
>>> curve = X_evol[0]
>>> curve
```
but get no output coordinates?

**Comment by tarak77** [comment]
THis is what i get

```
>>> data = np.load('lam1_1.npz')['summary'].item()
>>> data
{'initialized_curve': array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]]), 'weight_secondroughness': 0.0, 'uuid': u'e00aca88-cefc-4ffd-b310-58ef37db02471', 'X_evol': [None], 'method': u'BFGS', u'weight_uniform_spacing': 0.0, 'json_task': {u'uuid': u'e00aca88-cefc-4ffd-b310-58ef37db02471', u'parameters': {u'a': -3.0, u'b': 1.0, u'term_weights': {u'population prior': 0.0, 'h2': 1.0, u'data': 1.0, 'firstroughness': 0.0, 'h1': 0.0, u'smoothing': 1.0, u'shape prior': 0.0, 'scaledsecondroughness': 0.0, u'uniform spacing': 0.0, 'scaledfirstroughness': 0.0, 'secondroughness': 0.0}}, 'store_task': True, u'randomize_initialization': False, u'check_jacobian': False, u'usewarmstarts': True, u'file_names': {u'inputdir': u'data/', u'pairwise_contact_matrix': u'NXT-43_chr1_250kb_new.npy', u'outputdir': u'results_NXT-43_250kb/', u'output_filename': u'e00aca88-cefc-4ffd-b310-58ef37db02471.npy'}, u'taskname': u'e00aca88-cefc-4ffd-b310-58ef37db02471', u'data': {u'pairwise_contact_matrix': array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 5.3970127, 1.7211102,
        0.       ],
       [0.       , 0.       , 0.       , ..., 1.7211102, 3.293178 ,
        0.9164144],
       [0.       , 0.       , 0.       , ..., 0.       , 0.9164144,
        0.       ]]), 'pairwise_combinations': array([[  0,   1],
       [  0,   2],
       [  0,   3],
       ...,
       [763, 764],
       [763, 765],
       [764, 765]]), 't': array([0.        , 0.00126904, 0.00253807, 0.00380711, 0.00507614,
       0.00634518, 0.00761421, 0.00888325, 0.01015228, 0.01142132,
       0.01269036, 0.01395939, 0.01522843, 0.01649746, 0.0177665 ,
       0.01903553, 0.02030457, 0.0215736 , 0.02284264, 0.02411168,
       0.02538071, 0.02664975, 0.02791878, 0.02918782, 0.03045685,
       0.03172589, 0.03299492, 0.03426396, 0.03553299, 0.03680203,
       0.03807107, 0.0393401 , 0.04060914, 0.04187817, 0.04314721,
       0.04441624, 0.04568528, 0.04695431, 0.04822335, 0.04949239,
       0.05076142, 0.05203046, 0.05329949, 0.05456853, 0.05583756,
       0.0571066 , 0.05837563, 0.05964467, 0.06091371, 0.06218274,
       0.06345178, 0.06472081, 0.06598985, 0.06725888, 0.06852792,
       0.06979695, 0.07106599, 0.07233503, 0.07360406, 0.0748731 ,
       0.07614213, 0.07741117, 0.0786802 , 0.07994924, 0.08121827,
       0.08248731, 0.08375635, 0.08502538, 0.08629442, 0.08756345,
       0.08883249, 0.09010152, 0.09137056, 0.09263959, 0.09390863,
       0.09517766, 0.0964467 , 0.09771574, 0.09898477, 0.10025381,
       0.10152284, 0.10279188, 0.10406091, 0.10532995, 0.10659898,
       0.10786802, 0.10913706, 0.11040609, 0.11167513, 0.11294416,
       0.1142132 , 0.11548223, 0.11675127, 0.1180203 , 0.11928934,
       0.12055838, 0.12182741, 0.12309645, 0.12436548, 0.12563452,
       0.12690355, 0.12817259, 0.12944162, 0.13071066, 0.1319797 ,
       0.13324873, 0.13451777, 0.1357868 , 0.13705584, 0.13832487,
       0.13959391, 0.14086294, 0.14213198, 0.14340102, 0.14467005,
       0.14593909, 0.14720812, 0.14847716, 0.14974619, 0.15101523,
       0.15228426, 0.1535533 , 0.15482234, 0.15609137, 0.15736041,
       0.15862944, 0.15989848, 0.16116751, 0.16243655, 0.16370558,
       0.16497462, 0.16624365, 0.16751269, 0.16878173, 0.17005076,
       0.1713198 , 0.17258883, 0.17385787, 0.1751269 , 0.17639594,
       0.17766497, 0.17893401, 0.18020305, 0.18147208, 0.18274112,
       0.18401015, 0.18527919, 0.18654822, 0.18781726, 0.18908629,
       0.19035533, 0.19162437, 0.1928934 , 0.19416244, 0.19543147,
       0.19670051, 0.19796954, 0.19923858, 0.20050761, 0.20177665,
       0.20304569, 0.20431472, 0.20558376, 0.20685279, 0.20812183,
       0.20939086, 0.2106599 , 0.21192893, 0.21319797, 0.21446701,
       0.21573604, 0.21700508, 0.21827411, 0.21954315, 0.22081218,
       0.22208122, 0.22335025, 0.22461929, 0.22588832, 0.22715736,
       0.2284264 , 0.22969543, 0.23096447, 0.2322335 , 0.23350254,
       0.23477157, 0.23604061, 0.23730964, 0.23857868, 0.23984772,
       0.24111675, 0.24238579, 0.24365482, 0.24492386, 0.24619289,
       0.24746193, 0.24873096, 0.25      , 0.25126904, 0.25253807,
       0.25380711, 0.25507614, 0.25634518, 0.25761421, 0.25888325,
       0.26015228, 0.26142132, 0.26269036, 0.26395939, 0.26522843,
       0.26649746, 0.2677665 , 0.26903553, 0.27030457, 0.2715736 ,
       0.27284264, 0.27411168, 0.27538071, 0.27664975, 0.27791878,
       0.27918782, 0.28045685, 0.28172589, 0.28299492, 0.28426396,
       0.28553299, 0.28680203, 0.28807107, 0.2893401 , 0.29060914,
       0.29187817, 0.29314721, 0.29441624, 0.29568528, 0.29695431,
       0.29822335, 0.29949239, 0.30076142, 0.30203046, 0.30329949,
       0.30456853, 0.30583756, 0.3071066 , 0.30837563, 0.30964467,
       0.31091371, 0.31218274, 0.31345178, 0.31472081, 0.31598985,
       0.31725888, 0.31852792, 0.31979695, 0.32106599, 0.32233503,
       0.32360406, 0.3248731 , 0.32614213, 0.32741117, 0.3286802 ,
       0.32994924, 0.33121827, 0.33248731, 0.33375635, 0.33502538,
       0.33629442, 0.33756345, 0.33883249, 0.34010152, 0.34137056,
       0.34263959, 0.34390863, 0.34517766, 0.3464467 , 0.34771574,
       0.34898477, 0.35025381, 0.35152284, 0.35279188, 0.35406091,
       0.35532995, 0.35659898, 0.35786802, 0.35913706, 0.36040609,
       0.36167513, 0.36294416, 0.3642132 , 0.36548223, 0.36675127,
       0.3680203 , 0.36928934, 0.37055838, 0.37182741, 0.37309645,
       0.37436548, 0.37563452, 0.37690355, 0.37817259, 0.37944162,
       0.38071066, 0.3819797 , 0.38324873, 0.38451777, 0.3857868 ,
       0.38705584, 0.38832487, 0.38959391, 0.39086294, 0.39213198,
       0.39340102, 0.39467005, 0.39593909, 0.39720812, 0.39847716,
       0.39974619, 0.40101523, 0.40228426, 0.4035533 , 0.40482234,
       0.40609137, 0.40736041, 0.40862944, 0.40989848, 0.41116751,
       0.41243655, 0.41370558, 0.41497462, 0.41624365, 0.41751269,
       0.41878173, 0.42005076, 0.4213198 , 0.42258883, 0.42385787,
       0.4251269 , 0.42639594, 0.42766497, 0.42893401, 0.43020305,
       0.43147208, 0.43274112, 0.43401015, 0.43527919, 0.43654822,
       0.43781726, 0.43908629, 0.44035533, 0.44162437, 0.4428934 ,
       0.44416244, 0.44543147, 0.44670051, 0.44796954, 0.44923858,
       0.45050761, 0.45177665, 0.45304569, 0.45431472, 0.45558376,
       0.45685279, 0.45812183, 0.45939086, 0.4606599 , 0.46192893,
       0.46319797, 0.46446701, 0.46573604, 0.46700508, 0.46827411,
       0.46954315, 0.47081218, 0.47208122, 0.47335025, 0.47461929,
       0.47588832, 0.47715736, 0.4784264 , 0.47969543, 0.48096447,
       0.4822335 , 0.48350254, 0.48477157, 0.48604061, 0.48730964,
       0.48857868, 0.48984772, 0.49111675, 0.49238579, 0.49365482,
       0.49492386, 0.49619289, 0.49746193, 0.49873096, 0.5       ,
       0.50126904, 0.50253807, 0.50380711, 0.50507614, 0.50634518,
       0.50761421, 0.50888325, 0.51015228, 0.51142132, 0.51269036,
       0.51395939, 0.51522843, 0.51649746, 0.5177665 , 0.51903553,
       0.52030457, 0.5215736 , 0.52284264, 0.52411168, 0.52538071,
       0.52664975, 0.52791878, 0.52918782, 0.53045685, 0.53172589,
       0.53299492, 0.53426396, 0.53553299, 0.53680203, 0.53807107,
       0.5393401 , 0.54060914, 0.54187817, 0.54314721, 0.54441624,
       0.54568528, 0.54695431, 0.54822335, 0.54949239, 0.55076142,
       0.55203046, 0.55329949, 0.55456853, 0.55583756, 0.5571066 ,
       0.55837563, 0.55964467, 0.56091371, 0.56218274, 0.56345178,
       0.56472081, 0.56598985, 0.56725888, 0.56852792, 0.56979695,
       0.57106599, 0.57233503, 0.57360406, 0.5748731 , 0.57614213,
       0.57741117, 0.5786802 , 0.57994924, 0.58121827, 0.58248731,
       0.58375635, 0.58502538, 0.58629442, 0.58756345, 0.58883249,
       0.59010152, 0.59137056, 0.59263959, 0.59390863, 0.59517766,
       0.5964467 , 0.59771574, 0.59898477, 0.60025381, 0.60152284,
       0.60279188, 0.60406091, 0.60532995, 0.60659898, 0.60786802,
       0.60913706, 0.61040609, 0.61167513, 0.61294416, 0.6142132 ,
       0.61548223, 0.61675127, 0.6180203 , 0.61928934, 0.62055838,
       0.62182741, 0.62309645, 0.62436548, 0.62563452, 0.62690355,
       0.62817259, 0.62944162, 0.63071066, 0.6319797 , 0.63324873,
       0.63451777, 0.6357868 , 0.63705584, 0.63832487, 0.63959391,
       0.64086294, 0.64213198, 0.64340102, 0.64467005, 0.64593909,
       0.64720812, 0.64847716, 0.64974619, 0.65101523, 0.65228426,
       0.6535533 , 0.65482234, 0.65609137, 0.65736041, 0.65862944,
       0.65989848, 0.66116751, 0.66243655, 0.66370558, 0.66497462,
       0.66624365, 0.66751269, 0.66878173, 0.67005076, 0.6713198 ,
       0.67258883, 0.67385787, 0.6751269 , 0.67639594, 0.67766497,
       0.67893401, 0.68020305, 0.68147208, 0.68274112, 0.68401015,
       0.68527919, 0.68654822, 0.68781726, 0.68908629, 0.69035533,
       0.69162437, 0.6928934 , 0.69416244, 0.69543147, 0.69670051,
       0.69796954, 0.69923858, 0.70050761, 0.70177665, 0.70304569,
       0.70431472, 0.70558376, 0.70685279, 0.70812183, 0.70939086,
       0.7106599 , 0.71192893, 0.71319797, 0.71446701, 0.71573604,
       0.71700508, 0.71827411, 0.71954315, 0.72081218, 0.72208122,
       0.72335025, 0.72461929, 0.72588832, 0.72715736, 0.7284264 ,
       0.72969543, 0.73096447, 0.7322335 , 0.73350254, 0.73477157,
       0.73604061, 0.73730964, 0.73857868, 0.73984772, 0.74111675,
       0.74238579, 0.74365482, 0.74492386, 0.74619289, 0.74746193,
       0.74873096, 0.75      , 0.75126904, 0.75253807, 0.75380711,
       0.75507614, 0.75634518, 0.75761421, 0.75888325, 0.76015228,
       0.76142132, 0.76269036, 0.76395939, 0.76522843, 0.76649746,
       0.7677665 , 0.76903553, 0.77030457, 0.7715736 , 0.77284264,
       0.77411168, 0.77538071, 0.77664975, 0.77791878, 0.77918782,
       0.78045685, 0.78172589, 0.78299492, 0.78426396, 0.78553299,
       0.78680203, 0.78807107, 0.7893401 , 0.79060914, 0.79187817,
       0.79314721, 0.79441624, 0.79568528, 0.79695431, 0.79822335,
       0.79949239, 0.80076142, 0.80203046, 0.80329949, 0.80456853,
       0.80583756, 0.8071066 , 0.80837563, 0.80964467, 0.81091371,
       0.81218274, 0.81345178, 0.81472081, 0.81598985, 0.81725888,
       0.81852792, 0.81979695, 0.82106599, 0.82233503, 0.82360406,
       0.8248731 , 0.82614213, 0.82741117, 0.8286802 , 0.82994924,
       0.83121827, 0.83248731, 0.83375635, 0.83502538, 0.83629442,
       0.83756345, 0.83883249, 0.84010152, 0.84137056, 0.84263959,
       0.84390863, 0.84517766, 0.8464467 , 0.84771574, 0.84898477,
       0.85025381, 0.85152284, 0.85279188, 0.85406091, 0.85532995,
       0.85659898, 0.85786802, 0.85913706, 0.86040609, 0.86167513,
       0.86294416, 0.8642132 , 0.86548223, 0.86675127, 0.8680203 ,
       0.86928934, 0.87055838, 0.87182741, 0.87309645, 0.87436548,
       0.87563452, 0.87690355, 0.87817259, 0.87944162, 0.88071066,
       0.8819797 , 0.88324873, 0.88451777, 0.8857868 , 0.88705584,
       0.88832487, 0.88959391, 0.89086294, 0.89213198, 0.89340102,
       0.89467005, 0.89593909, 0.89720812, 0.89847716, 0.89974619,
       0.90101523, 0.90228426, 0.9035533 , 0.90482234, 0.90609137,
       0.90736041, 0.90862944, 0.90989848, 0.91116751, 0.91243655,
       0.91370558, 0.91497462, 0.91624365, 0.91751269, 0.91878173,
       0.92005076, 0.9213198 , 0.92258883, 0.92385787, 0.9251269 ,
       0.92639594, 0.92766497, 0.92893401, 0.93020305, 0.93147208,
       0.93274112, 0.93401015, 0.93527919, 0.93654822, 0.93781726,
       0.93908629, 0.94035533, 0.94162437, 0.9428934 , 0.94416244,
       0.94543147, 0.94670051, 0.94796954, 0.94923858, 0.95050761,
       0.95177665, 0.95304569, 0.95431472, 0.95558376, 0.95685279,
       0.95812183, 0.95939086, 0.9606599 , 0.96192893, 0.96319797,
       0.96446701, 0.96573604, 0.96700508, 0.96827411, 0.96954315,
       0.97081218, 0.97208122, 0.97335025, 0.97461929, 0.97588832,
       0.97715736, 0.9784264 , 0.97969543, 0.98096447, 0.9822335 ,
       0.98350254, 0.98477157, 0.98604061, 0.98730964, 0.98857868,
       0.98984772, 0.99111675, 0.99238579, 0.99365482, 0.99492386,
       0.99619289, 0.99746193, 0.99873096, 1.        ]), 'off_diagonal': 1, 'index_mississing': array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11, 341,
       342, 343, 344, 345, 346, 347, 348, 349, 707, 740]), 'missing_rowsum_threshold': 0, 'initialized_curve': array([[-0.25224362, -0.24014666, -0.19394432, ...,  0.42102352,
        -0.09264019,  0.0310019 ],
       [-0.39188234, -0.07827689,  0.15406455, ...,  0.38282281,
         0.25279416, -0.22675254],
       [ 0.45685327, -0.27940228, -0.36075806, ...,  0.11614733,
        -0.40505945, -0.09455649]])}, u'options': {u'maxitr': 100000, u'gradient tolerance': 1e-05, u'method': u'BFGS', 'minimum energy': -inf, u'display': True, u'store': False}}, 'E_evol': array([], dtype=float64), 'computation_time': 0.2236180305480957, u'weight_population_prior': 0.0, 'weight_scaledsecondroughness': 0.0, u'weight_data': 1.0, 'weight_scaledfirstroughness': 0.0, u'weight_smoothing': 1.0, u'weight_shape_prior': 0.0, 'a': -3.0, 'b': 'nan', 'weight_h2': 1.0, 'd': 3, 'weight_h1': 0.0, 'n': 789, 'weight_firstroughness': 0.0}
```
I know that my input .npy file is not empty, chr1 at 250kb resolution:
![chr1](https://user-images.githubusercontent.com/32019333/46575751-82fb2600-c989-11e8-8a42-48e8873b4ae2.png)

But for some reason `simba3d -r ` command doesn't iterate till tolerance value. Is there something i am doing wrong at my end?

Any help would be great!

P.S. i tried on linux, my Mac  for both `command_line_tutorial `and` creating_tasklists_with_python `

**Comment by michael-m-rosenthal** [comment]
The curve is initized as a Nan for some reason

**Comment by tarak77** [comment]
Since i am not giving any initial curve, do i need to set some of parameters to be True? 
This is how my `create_warmstarts_tasklists.py` looks like

[file.txt](https://github.com/nerettilab/SIMBA3D/files/2453459/file.txt)

**Comment by michael-m-rosenthal** [comment]
So the curve should automatically initialize randomly if you don't provide
an input regardless and it should output it in the results. It should not
be Nan's. That is the only thing I can see right now. You can try
initializing the curve and see if that helps. I can try and run it myself
and see if I can reproduce the error.

**Comment by tarak77** [comment]
I did try to initialize randomly but it still produced the same error.
 Actually i also tried the example scripts in` creating_tasklists_with_python` for creating tasklists with following defaults:

```
"initialized_curve"         : 'initialized_curve.npy',
"pairwise_contact_matrix" : 'simulated_contact_matrix.npy',
```
but still same error.

**Comment by michael-m-rosenthal** [comment]
The example doesn't work for you either?

**Comment by michael-m-rosenthal** [comment]
Are you using python 2.7?

**Comment by tarak77** [comment]
Sorry, i tried again and the example scripts works for py27. 
There might be a mistake in my input contact matrix.  I will try again and let you know.

**Comment by michael-m-rosenthal** [comment]
Glad it is working.

Sorry, I really do need to update everything to python 3.

One thing that is slowing me down is that the npz and npy numpy files
binaries are not compatible between python 2 and 3.  Python3 cannot read
python 2 numpy files (and the other way around).  The mat file format
doesn't have this issue, but I didn't want to default to a format made for
proprietary software. The sensible alternative is json, but it requires
special serialization of python objects.

I do need to work on the file format input and output.


On Oct 7, 2018 10:13 PM, "Tarak Shisode" <notifications@github.com> wrote:

Sorry, i tried again and the example scripts works for py27.
There might be a mistake in my input contact matrix. I will try again and
let you know.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/7#issuecomment-427712556>,
or mute
the thread

**Comment by tarak77** [comment]
Okay, I see.
Still trying to figure out the issue. Could you try to use the following .txt input file to convert to .npy. And then using that data in `create_warmstarts_tasklist.py` code without any initialization curve and see if you get any results using` simba3d -r warmstart_tasklists.txt` ?
[NXT-43.chr3.250kb.kr.hicpro.txt](https://github.com/nerettilab/SIMBA3D/files/2457457/NXT-43.chr3.250kb.kr.hicpro.txt)

**Comment by tarak77** [comment]
Hi @michael-m-rosenthal I tried to download this repo again for py27 but still couldn't figure it out! The initial curve is not being initialized randomly, still getting NaNs- and hence the output files are empty.
Any help?

**Comment by michael-m-rosenthal** [comment]
Sorry,

I hadn't been able to work on it since Hurricane Michael. I will let you
know when I'm able to try and duplicate the issue.

**Comment by tarak77** [comment]
Sure, no worries!

**Comment by michael-m-rosenthal** [comment]
Hi,

I just wanted to give you an update.

Things are starting to return to normal so I should be able to resume
working on issues soon.

I appreciate you testing out the code and bringing up issues and I am sorry
it has taken so long to get back with you.


On Oct 16, 2018 8:39 PM, "Tarak Shisode" <notifications@github.com> wrote:

Sure, no worries!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/7#issuecomment-430458938>,
or mute
the thread

**Comment by tarak77** [comment]
That's great! No need to be sorry. What I am concerned is working on high resolution, say 100kb matrices. Due to the sparseness, simba3d seems to give `initialized_curve:None, X_evol:None`. I could be wrong but it would be good to confirm.

**Comment by michael-m-rosenthal** [comment]
SIMBA3D has the same loglikehood as used by pastis but it adds 3 optional
penalty terms. One enforces uniform spacing of the node, the next one
enforces some smoothness, and the third allows you to fill in gaps with
population data. I set the default penalty weights to zero, but maybe there
is some more logical default we could use in general. The penalty terms
should make the gradient stable if the data is sparse, so you should not
get Nan's if you use the penalties. If you leave the penalty weights all
zero, then it will probably not be stable for single cell 100kb data.

On Oct 30, 2018 9:28 PM, "Tarak Shisode" <notifications@github.com> wrote:

That's great! No need to be sorry. What I am concerned is working on high
resolution, say 100kb matrices. Due to the sparseness, simba3d seems to
give X_evol:None. I could be wrong but it would be good to confirm.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/7#issuecomment-434539064>,
or mute
the thread

**Comment by tarak77** [comment]
But I do set lambda_1 and lambda_2 to be nonzero(vary them from 0 to 11). For some reason at that resolution I am getting NaNs. Maybe I will have to check for other values?

**Comment by michael-m-rosenthal** [comment]
I was able to get SIMBA3D to run on your data. If it is agreeable to you, I
would like to make this an example in the code with the dataset posted.

I speculate that the issue might arise in the way you converted the text
file into a npy file, but it is hard to tell. It could also be an issue
with the npy format. Unfortunately, numpy binary files are not readable
between python3 and python2, so I am working on an alternative format saved
as either json and mat. I have made a new sparse matrix format which I hope
will be easier to use and will take up less hard drive space.

If it is okay with you to post the data I will push it as soon as I clean
up to tutorial.

My best,
Michael Rosenthal

On Nov 3, 2018 8:17 PM, "Tarak Shisode" <notifications@github.com> wrote:

But I do set lambda_1 and lambda_2 to be nonzero. For some reason at that
resolution I am getting NaNs.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/nerettilab/SIMBA3D/issues/7#issuecomment-435633848>,
or mute
the thread

**Comment by tarak77** [comment]
Sure you can. What parameters value did you set for lambda_1 and lambda_2?

Again i am using 100kb contact matrices for all chromosomes in a cell and varying lambda_1 and lambda_2 to be nonzero(vary them from 0 to 11)
1. The following compressed file has both .txt and .npy matrix files for chromosome 1 at 100kb for a particular cell:
[1.100000bp.tar.gz](https://github.com/nerettilab/SIMBA3D/files/2563826/1.100000bp.tar.gz)

I guess due to the sparseness and the parameter values, simba3d seems to give `initialized_curve:None, X_evol:None` ? I dont understand how to set the parameter values?

2. Moreover, i tried for another cell, chr1, 100kb:
[1.100000bp.tar.gz](https://github.com/nerettilab/SIMBA3D/files/2563840/1.100000bp.tar.gz)

Seems to run for days with the above parameters.

Any help will be great!
