### ISSUE TITLE
what is srvf in create_simulated_data.py code?

### ISSUE THREAD

**Issue by tarak77** [nerettilab/SIMBA3D#9]
Hi Michael,
In the` create_simulated_data.py` file, you use `srvf.interp` function to resample your original spiral data for a fixed number of points. What exactly is the srvf function?

Can I use that function elsewhere? For instance I am trying to compute the pairwise Euclidean distance between the coordinates of the two curves, but for some reason the number of points vary between those. I was wondering if by using the srvf.interp function to match the number of points, I can calculate the distance?

Any help would be great!

**Comment by michael-m-rosenthal** [comment]
It is an incomplete library for representing 3D curves as square root
velocities. It doesn't include the dynamic programming needed for point
registration though.

If you know the registration between the two points then you can use my
interpolator to resample points. It is fairly straightforward to implement
it yourself.

If need to solve for registration, there are Matlab implantations of this
at

http://ssamg.stat.fsu.edu/software

I believe there's a python library and an R package written for it as well,
but I don't know what it is called.

For more details see 'Functional and Shape Data Analysis'
